Dev tddominik
Th3Ph4nt0m/TD-Bot pull request #13
Opened 2020-11-10 20:59 UTC by domlen2003

2020-11-11 21:05 UTC, Taucher2003 requested changes
Ich würde Kleinigkeiten ändern, die genaueren Infos stehen in den Kommentaren an den Codestellen.

2020-11-11 21:05 UTC, Taucher2003 commented on src/main/java/de/th3ph4nt0m/tdbot/utils/MessageCenter.java
> +            builder.addField(info.name,info.description,false);
Die Überprüfung, ob man berechtigt ist, einen Command auszuführen, würde ich hier durchführen und nicht im Help Command selber

2020-11-11 21:21 UTC, domlen2003 commented on src/main/java/de/th3ph4nt0m/tdbot/core/CommandHandler.java
> +				addCommand(cmd);
Man kann ja weiterhin manuell hinzufügen wenn es denn benötigt würde

2020-11-11 21:24 UTC, domlen2003 commented on src/main/java/de/th3ph4nt0m/tdbot/utils/MessageCenter.java
> +            builder.addField(info.name,info.description,false);
Geht natürlich auch aber eigentlich sollte das Messagecenter nur das Nachrichten versenden an sich übernehmen und keine "Entscheidung" mehr über die Nachricht selbst treffen. 

Also war bisher so

2020-11-11 21:28 UTC, domlen2003 commented on src/main/java/de/th3ph4nt0m/tdbot/utils/MessageCenter.java
> +            builder.addField(info.name,info.description,false);
Ansonsten aber danke für die Änderungsvorschläge 👌

2020-11-11 21:48 UTC, domlen2003 commented on src/main/java/de/th3ph4nt0m/tdbot/core/CommandHandler.java
> +				addCommand(cmd);
Aliases wären doch theoretisch auch möglich wenn man den Namen in der CommandInfo als nen Array von Strings definieren würde und jeden einzelnen Namen/invoke in die map packt?

Oder hab ich falsch verstanden was mit alias gemeint ist?

2020-11-12 05:50 UTC, Taucher2003 commented on src/main/java/de/th3ph4nt0m/tdbot/core/CommandHandler.java
> +				addCommand(cmd);
Theoretisch würde das gehen.

2020-11-12 05:52 UTC, Taucher2003 commented on src/main/java/de/th3ph4nt0m/tdbot/utils/MessageCenter.java
> +            builder.addField(info.name,info.description,false);
Das war ja nur ein Vorschlag, wenn ihr das weiterhin so handhaben wollt, könnt ihr das gerne so machen

2020-11-24 18:43 UTC, Th3Ph4nt0m commented
Unfortunately I do not see the point behind this system. I regret that the changes cannot be accepted.

2020-11-24 18:43 UTC, closed without merging