Dev tddominik
Th3Ph4nt0m/TD-Bot pull request #15
Opened 2020-11-24 18:52 UTC by domlen2003

Auto Registration removed but still useful features added

2020-11-25 10:25 UTC, Th3Ph4nt0m commented on src/main/java/de/th3ph4nt0m/tdbot/interfaces/ICommand.java
> +    //returns true when command is unsafe to run in current conditions
Please use [Javadocs Comments](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html)

2020-11-25 10:25 UTC, Th3Ph4nt0m commented on src/main/java/de/th3ph4nt0m/tdbot/interfaces/ICommand.java
> +    //calls the command
Please use [Javadocs comments](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html)

2020-11-25 10:27 UTC, Th3Ph4nt0m commented on src/main/java/de/th3ph4nt0m/tdbot/core/CommandHandler.java
> +		//addCommands();
Remove unused methods please.

2020-11-25 10:27 UTC, Th3Ph4nt0m requested changes
Please change the points i wrote as comments.

2020-11-28 12:13 UTC, Th3Ph4nt0m commented
As you can see, your latest changes to the level system have just been incorporated into this PR, so I cannot accept them. Let's work best with feature branches (e.g. feature/levelsystem) to improve the workflow.

2020-12-02 18:37 UTC, domlen2003 commented
Könnten der liebe Herr Ph4nt0m bitte den verkackten pullrequest annehmen.

2020-12-02 18:38 UTC, domlen2003 commented
Wäre coll thx

2020-12-03 21:10 UTC, Th3Ph4nt0m approved these changes
Tested without a database, but should work.

2020-12-03 21:10 UTC, merged